### ISSUE TITLE
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

### ISSUE THREAD

**Issue by WestbrookZero** [SuyashMore/MevonAI-Speech-Emotion-Recognition#2]
when i use wav file, it is error:
Traceback (most recent call last):
  File "D:/Projects/Audio/Emotion/SER/MevonAI-Speech-Emotion-Recognition/src/speakerDiarization.py", line 253, in <module>
    main("filter_"+FILE_N, embedding_per_second=0.6, overlap_rate=0.4)
  File "D:/Projects/Audio/Emotion/SER/MevonAI-Speech-Emotion-Recognition/src/speakerDiarization.py", line 170, in main
    feats = np.array(feats)[:,0,:].astype(float)  # [splits, embedding dim]
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

**Comment by SuyashMore** [comment]
Can you please share the .wav file?

**Comment by WestbrookZero** [comment]
wav file can't upload github , when i set embedding_per_second=1.0, overlap_rate=0.5 , it is right.
