### ISSUE TITLE
error for adding audio folder 

### ISSUE THREAD

**Issue by har790** [SuyashMore/MevonAI-Speech-Emotion-Recognition#7]
hey there, 
 I tried a lot to add audio folder but it throws error, even I made one folder for one file and changed the code but still  its shows error  
as such :-
Traceback (most recent call last):
  File "speechEmotionRecognition.py", line 62, in <module>
    bk.diarizeFromFolder(f'{INPUT_FOLDER_PATH}{subdir}{"/"}',(f'{OUTPUT_FOLDER_PATH}{subdir}{"/"}'))
  File "/content/emotion/src/bulkDiarize.py", line 29, in diarizeFromFolder
    diarizeAudio(TOTAL_PATH,TOTAL_OUTPUT_PATH,expectedSpeakers=2)
  File "/content/emotion/src/speakerDiarization.py", line 242, in diarizeAudio
    main("filterTemp.wav", embedding_per_second=0.6, overlap_rate=0.4,exportFile=exportFile,expectedSpeakers=expectedSpeakers)
  File "/content/emotion/src/speakerDiarization.py", line 170, in main
    feats = np.array(feats)[:,0,:].astype(float)  # [splits, embedding dim]
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

please could u explain me .

**Comment by SuyashMore** [comment]
Check this out #2
